### ISSUE TITLE
Data Structures 1

### ISSUE THREAD

**Issue by Arushi-maker** [Arushi-maker/students#12]
[Link to Blog](http://127.0.0.1:4200/student//2024/04/17/DataStructureWriteUp_IPYNB_2_.html)

**Comment by avanthikadaita** [comment]
Graded by: Avanthika Daita
Score: 92%
The blog isn't working so I looked in the notebooks for it. 

# Collections
Completeness 1/1, Accuracy 0.6/1
Database and tester code is shown
Clear explanation of the code paired with the images
# Lists and Dictionaries
Completeness 1/1, Accuracy 0.8/1
Shows using keys to access the user dictionary
Debugging seems to be missing but it is attempted
# APIs and JSON
Completeness 1/1, Accuracy 1/1
Screenshots that are done are accurate
Postman request shows errors and bodies
# Frontend
Completeness: 1/1, Accuracy 0.8/1
Mostly correct
# Algorithm Analysis
Completeness 1/1, Accuracy 1/1
I can tell you know these concepts well
